### ISSUE TITLE
just some Compass windows thing.

### ISSUE THREAD

**Issue by ghost** [RyuuKitsune/ElectronicObserver#16]
enemy fleet report is always -1
enemy plane slot is always 0
furn coin box (med) is untranslated :o
not exactly issues but.

**Comment by RyuuKitsune** [comment]
Enemy IDs was intentional, though is now changed in 1.6+. Plane slot is 0, this is intentional, it is currently impossible to determine enemy fleet slots via normal methods, so it'll stay that way until it becomes possible to redetermine the amount of planes an enemy fleet has. As for the furniture coin box, I will translate that before next release. Thanks!

**Comment by ghost** [comment]
uhm another one.fleet and compass window plane slots are black even on black theme. I'm looking forward to the next version :D thanks for translating EO :D

**Comment by ghost** [comment]
this was for 1.4.4 >.< didnt saw the updates earlier.
